

export const loginStatus={
  FAILED : 'FAILED',
  SUCCESS : 'SUCCESS',
  REGISTERED : "REGISTERED"
}



export const links = {
  activity: "admin/activity",
  list_activities: "admin/list-activities",
  bank: "admin/bank",
  list_banks: "admin/list-banks",
  bank_account_number: "admin/bank-account-number",
  list_bank_account_numbers: "admin/list-bank-account-numbers",
  bank_account_transaction: "admin/bank-account-transaction",
  list_bank_account_transactions: "admin/list-bank-account-transactions",
  chart_of_account: "admin/chart-of-account",
  list_chart_of_accounts: "admin/list-chart-of-accounts",
  chart_of_accounts_group: "admin/chart-of-accounts-group",
  list_chart_of_accounts_groups: "admin/list-chart-of-accounts-groups",
  cheque_type: "admin/cheque-type",
  list_cheque_types: "admin/list-cheque-types",
  code_generator: "admin/code-generator",
  list_code_generators: "admin/list-code-generators",
  general_ledger: "admin/general-ledger",
  list_general_ledgers: "admin/list-general-ledgers",
  petty_cash_voucher: "admin/petty-cash-voucher",
  list_petty_cash_vouchers: "admin/list-petty-cash-vouchers",
  petty_cash_voucher_item: "admin/petty-cash-voucher-item",
  list_petty_cash_voucher_items: "admin/list-petty-cash-voucher-items",
  country: "admin/country",
  list_countries: "admin/list-countries",
  currency: "admin/currency",
  list_currencies: "admin/list-currencies",
  mobile_service_provider: "admin/mobile-service-provider",
  list_mobile_service_providers: "admin/list-mobile-service-providers",
  organisation: "admin/organisation",
  list_organisations: "admin/list-organisations",
  organisation_branch: "admin/organisation-branch",
  list_organisation_branches: "admin/list-organisation-branches",
  region: "admin/region",
  list_regions: "admin/list-regions",
  sms_provider: "admin/sms-provider",
  list_sms_providers: "admin/list-sms-providers",
  sms_template: "admin/sms-template",
  list_sms_templates: "admin/list-sms-templates",
  system_default: "admin/system-default",
  list_system_defaults: "admin/list-system-defaults",
  system_task_type: "admin/system-task-type",
  list_system_task_types: "admin/list-system-task-types",
  tariff: "admin/tariff",
  list_tariffs: "admin/list-tariffs",
  transaction_category: "admin/transaction-category",
  list_transaction_categories: "admin/list-transaction-categories",
  transaction_charge: "admin/transaction-charge",
  list_transaction_charges: "admin/list-transaction-charges",
  transaction_setup: "admin/transaction-setup",
  list_transaction_setups: "admin/list-transaction-setups",
  list_pos_devices: "business/list-pos-devices",
  pos_device: "business/pos-device",
  till: "business/till",
  list_tills: "business/list-tills",
  till_allowed_host: "business/till-allowed-host",
  list_till_allowed_hosts: "business/list-till-allowed-hosts",
  till_client_secret: "business/till-client-secret",
  list_till_client_secrets: "business/list-till-client-secrets",
  till_server_ip: "business/till-server-ip",
  list_till_server_ips: "business/list-till-server-ips",
  notification: "business/notification",
  list_notifications: "business/list-notifications",
  dispute: "management/dispute",
  list_disputes: "management/list-disputes",
  address: "management/address",
  list_addresses: "management/list-addresses",
  audit_log: "management/audit-log",
  list_audit_logs: "management/list-audit-logs",
  device: "management/device",
  list_devices: "management/list-devices",
  email_blacklist: "management/email-blacklist",
  list_email_blacklists: "management/list-email-blacklists",
  file_storage: "management/file-storage",
  list_file_storages: "management/list-file-storages",
  login_model: "management/login-model",
  list_login_models: "management/list-login-models",
  payment_request: "management/payment-request",
  list_payment_requests: "management/list-payment-requests",
  phone_blacklist: "management/phone-blacklist",
  list_phone_blacklists: "management/list-phone-blacklists",
  sms_blacklist: "management/sms-blacklist",
  list_sms_blacklists: "management/list-sms-blacklists",
  sms_model: "management/sms-model",
  list_sms_model: "management/list-sms-model",
  transaction: "management/transaction",
  list_transactions: "management/list-transactions",
  staff: "user/staff",
  list_staff: "user/list-staffs",
  user: "user/user",
  confirm_signup_otp: "user/confirm-signup-otp",
  role: "user/role",
  list_users: "user/list-users",
  list_roles: "user/list-roles",
  upload_user_profile_picture: "user/upload-user-profile-picture",
  activate_deactivate_user: "user/activate-deactivate-user",
  list_user_roles: "user/list-user-roles/{userId}",
  add_user_to_role: "user/add-user-to-role",
  reset_user_password: "user/reset-user-password",
  my_roles: "auth/my-roles",
  set_password: "auth/set-user-password-password",
  login: "auth/login",

  payment_method:"management/payment-method",
  payment_methods:"management/list-payment-method",

  cash_transaction:"business/cash-transaction",
  cash_transactions:"business/cash-transactions",

  merchant_invoice:"business/merchant-invoice",
  merchant_invoices:"business/list-merchant-invoices",

  merchant_transaction:"business/merchant-transactions",
  merchant_transactions:"business/list-merchant-transactions",

  bank_account:"business/bank-account",
  bank_accounts:"business/list-bank-accounts",

  escrow_transaction:"business/escrow-transaction",
  escrow_transactions:"business/list-escrow-transactions",

  forex_data:"business/forex-data/{id}",
  list_forex_data:"business/list-forex-data",

  standing_order_log:"business/standing-order-log/{id}",
  standing_order_logs:"business/list-standing-order-logs",

  standing_order:"management/standing-order",
  standing_orders:"management/standing-orders",

  list_email:"management/email",
  list_emails:"management/list-emails",

  mobile_money_account:"business/mobile-money-account",
  mobile_money_accounts:"business/list-mobile-money-accounts",

  user_payment_account:"business/user-payment-account",
  user_payment_accounts:"business/list-user-payment-accounts",

  user_transaction:"business/user-transaction",
  user_transactions:"business/list-user-transactions",

  list_language:"business/language",
  list_languages:"business/list-languages",

  login_request:"business/login-request",
  login_requests:"business/list-login-requests",

  c2b_request:"business/list-c2b-request",
  c2b_requests:"business/list-c2b-requests",

  signup_request:"business/signup-request",
  signup_requests:"business/list-signup-requests",
}

export const year= new Date().getFullYear();
